import tseslint from 'typescript-eslint';

/**
 * Node.js built-in modules that must be imported via the `node:` protocol so
 * they are unambiguously distinguished from npm packages with conflicting
 * names. Reference: https://nodejs.org/api/modules.html
 */
const NODE_BUILTINS = [
  'assert',
  'async_hooks',
  'buffer',
  'child_process',
  'cluster',
  'console',
  'constants',
  'crypto',
  'dgram',
  'diagnostics_channel',
  'dns',
  'domain',
  'events',
  'fs',
  'fs/promises',
  'http',
  'http2',
  'https',
  'inspector',
  'module',
  'net',
  'os',
  'path',
  'path/posix',
  'path/win32',
  'perf_hooks',
  'process',
  'punycode',
  'querystring',
  'readline',
  'repl',
  'stream',
  'stream/promises',
  'stream/web',
  'string_decoder',
  'sys',
  'timers',
  'timers/promises',
  'tls',
  'trace_events',
  'tty',
  'url',
  'util',
  'util/types',
  'v8',
  'vm',
  'wasi',
  'worker_threads',
  'zlib',
];

const restrictedNodeBuiltinImports = NODE_BUILTINS.map(name => ({
  name,
  message: `Import "node:${name}" instead of "${name}" so Node built-ins are unambiguously distinguished from npm packages — https://nodejs.org/api/modules.html`,
}));

export default tseslint.config(
  ...tseslint.configs.recommended,
  {
    // Node.js backend files
    files: ['src/**/*.ts', 'scripts/**/*.ts', 'test/**/*.ts', '*.js', '*.ts'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        console: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        BigInt: 'readonly',
        Promise: 'readonly',
        Symbol: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        WeakMap: 'readonly',
        WeakSet: 'readonly',
        Proxy: 'readonly',
        Reflect: 'readonly',
      },
    },
    rules: {
      // TypeScript hygiene
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_' },
      ],

      // Static-analysis safety nets — no runtime eval/Function constructor.
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',

      // Defensive coding defaults
      radix: 'error',
      'prefer-const': 'error',
      'no-var': 'error',
      'object-shorthand': 'error',
      'prefer-template': 'warn',
      'no-useless-escape': 'error',
      'no-useless-catch': 'error',
      'no-case-declarations': 'warn',
      'no-dupe-keys': 'error',
      'no-console': 'off',
      'no-unused-vars': 'off',

      // Force the `node:` protocol on Node built-ins.
      'no-restricted-imports': [
        'error',
        { paths: restrictedNodeBuiltinImports },
      ],
    },
  },
  {
    // Browser frontend files
    files: ['public/**/*.js', 'src/assets/**/*.ts'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        XMLHttpRequest: 'readonly',
        screen: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        NodeListOf: 'readonly',
        HTMLCollection: 'readonly',
        Element: 'readonly',
        HTMLElement: 'readonly',
        Document: 'readonly',
        Window: 'readonly',
        Node: 'readonly',
        HTMLFormElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLImageElement: 'readonly',
        Blob: 'readonly',
        FileReader: 'readonly',
        File: 'readonly',
        Event: 'readonly',
        EventSource: 'readonly',
        KeyboardEvent: 'readonly',
        MessageEvent: 'readonly',
        ClipboardEvent: 'readonly',
        PageTransitionEvent: 'readonly',
        MutationObserver: 'readonly',
        BigInt: 'readonly',
        Promise: 'readonly',
        Symbol: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        WeakMap: 'readonly',
        WeakSet: 'readonly',
        Proxy: 'readonly',
        Reflect: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
      'no-unused-vars': 'off',
      'prefer-const': 'off',
      'no-var': 'off',
      'object-shorthand': 'off',
      'prefer-template': 'off',
      'no-useless-escape': 'off',
      'no-case-declarations': 'off',
      'no-dupe-keys': 'error',
      'no-undef': 'error',
    },
  },
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'coverage/**',
      'test-results/**',
      '*.min.js',
      '*.bundle.js',
      '.git/**',
      '.worktrees/**',
      'parako-id-v*.tar.gz',
      'parako-id-v*.zip',
      'public/js/**',
      'ecosystem.config.cjs',
      'runtime/locales/.merged/**',
      'options/locales/.merged/**',
      'data/**',
    ],
  }
);
