import { defineConfig } from 'vitest/config';
import { resolve } from 'node:path';

export default defineConfig({
  test: {
    // Test environment
    environment: 'node',

    // Glob patterns for test files
    include: ['test/**/*.{test,spec}.{js,ts}'],
    // Playwright owns browser/protocol E2E specs. Importing those files in a
    // Vitest worker makes Playwright reject their top-level test declarations
    // and also pollutes unit-test coverage.
    exclude: ['node_modules', 'dist', '**/*.d.ts', 'test/e2e/**'],

    // Coverage configuration
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'lcov', 'html'],
      reportsDirectory: './test-results/coverage',
      include: ['src/**/*.{js,ts}', 'scripts/**/*.{js,mjs,ts}'],
      exclude: ['src/**/*.d.ts'],
      thresholds: {
        // Ratchet from the verified 2026-08-01 baseline. These use Vitest 4's
        // actual threshold shape so regressions fail instead of being ignored.
        branches: 16.01,
        functions: 21.19,
        lines: 18.22,
        statements: 18.07,
        // Exact file keys make the 100% requirement per-file without applying
        // the low transitional global ratchet to every legacy file.
        'scripts/testing/generate-production-artifact-manifest.mjs': {
          100: true,
        },
        'scripts/testing/production-artifact-manifest.ts': { 100: true },
        'scripts/create-release-manifest.mjs': { 100: true },
        'scripts/create-sbom.mjs': { 100: true },
        'scripts/extract-changelog.mjs': { 100: true },
        'scripts/tag-release.mjs': { 100: true },
        'scripts/build-manifest.js': { 100: true },
        'scripts/release.mjs': { 100: true },
        'scripts/manage/admin.ts': { 100: true },
        'scripts/manage/client.ts': { 100: true },
        'scripts/manage/client/add.ts': { 100: true },
        'scripts/manage/client/commands.ts': { 100: true },
        'scripts/manage/client/display.ts': { 100: true },
        'scripts/manage/client/index.ts': { 100: true },
        'scripts/manage/client/list.ts': { 100: true },
        'scripts/manage/client/local-client-manager.ts': { 100: true },
        'scripts/manage/client/local-types.ts': { 100: true },
        'scripts/manage/client/types.ts': { 100: true },
        'scripts/manage/database.ts': { 100: true },
        'scripts/manage/diagnostics.ts': { 100: true },
        'scripts/manage/keys.ts': { 100: true },
        'scripts/manage/systemd.ts': { 100: true },
        'scripts/manage/keys/commands.ts': { 100: true },
        'scripts/manage/keys/index.ts': { 100: true },
        'scripts/manage/shared/entrypoint.ts': { 100: true },
        'scripts/manage/shared/file.ts': { 100: true },
        'scripts/manage/shared/logger.ts': { 100: true },
        'scripts/manage/shared/types.ts': { 100: true },
        'scripts/manage/shared/utils.ts': { 100: true },
        'scripts/manage/systemd/commands.ts': { 100: true },
        'scripts/manage/systemd/generate.ts': { 100: true },
        'scripts/manage/systemd/install.ts': { 100: true },
        'scripts/manage/systemd/logs.ts': { 100: true },
        'scripts/manage/systemd/restart.ts': { 100: true },
        'scripts/manage/systemd/status.ts': { 100: true },
        'scripts/manage/systemd/uninstall.ts': { 100: true },
        'scripts/manage/systemd/validation.ts': { 100: true },
        'src/jobs/config.ts': { 100: true },
        'src/jobs/domains/background-tasks/handlers/data-import.handler.ts': {
          100: true,
        },
        'src/jobs/domains/background-tasks/handlers/jwks-rotation.handler.ts': {
          100: true,
        },
        'src/jobs/domains/background-tasks/handlers/password-breach-check.handler.ts':
          {
            100: true,
          },
        'src/jobs/domains/background-tasks/queue.ts': { 100: true },
        'src/jobs/domains/background-tasks/worker.ts': { 100: true },
        'src/jobs/processing/queue-manager.ts': { 100: true },
        'src/jobs/processing/worker-manager.ts': { 100: true },
        'src/jobs/redis.ts': { 100: true },
        'src/jobs/schedules/jwks-rotation.schedule.ts': { 100: true },
        'src/worker.ts': { 100: true },
        'src/app.ts': { 100: true },
        'src/index.ts': { 100: true },
        'src/assets/js/flash.ts': { 100: true },
        'src/assets/js/auth/oidc/consent.ts': { 100: true },
        'src/assets/js/admin/configuration/features.ts': { 100: true },
        'src/assets/js/admin/configuration/integrations.ts': { 100: true },
        'src/assets/js/admin/configuration/oidc-ttl.ts': { 100: true },
        'src/assets/js/admin/configuration/security.ts': { 100: true },
        'src/assets/js/admin/configuration/tenant-custom-identifiers.ts': {
          100: true,
        },
        'src/assets/js/admin/settings/custom-identifiers.ts': { 100: true },
        'src/assets/js/auth/account-recovery.ts': { 100: true },
        'src/assets/js/auth/email-verification.ts': { 100: true },
        'src/assets/js/auth/forgot-password.ts': { 100: true },
        'src/assets/js/auth/login.ts': { 100: true },
        'src/assets/js/auth/logout.ts': { 100: true },
        'src/assets/js/auth/mfa-verify.ts': { 100: true },
        'src/assets/js/auth/oidc/device-flow-code-input.ts': { 100: true },
        'src/assets/js/auth/oidc/device-flow-confirm-code.ts': { 100: true },
        'src/assets/js/auth/oidc/device-flow-success.ts': { 100: true },
        'src/assets/js/auth/oidc/login.ts': { 100: true },
        'src/assets/js/auth/oidc/logout.ts': { 100: true },
        'src/assets/js/auth/oidc/mfa.ts': { 100: true },
        'src/assets/js/auth/recovery-backup-codes.ts': { 100: true },
        'src/assets/js/auth/recovery-security-questions.ts': { 100: true },
        'src/assets/js/auth/recovery-sms.ts': { 100: true },
        'src/assets/js/auth/recovery-verify-code.ts': { 100: true },
        'src/assets/js/auth/register.ts': { 100: true },
        'src/assets/js/auth/reset-password.ts': { 100: true },
        'src/assets/js/auth/setup-mfa.ts': { 100: true },
        'src/assets/js/auth/social-contact-info.ts': { 100: true },
        'src/assets/js/auth/social-password-setup.ts': { 100: true },
        'src/assets/js/admin/configuration/common.ts': { 100: true },
        'src/assets/js/admin/data-transfer/data-transfer.ts': { 100: true },
        'src/assets/js/admin/layout.ts': { 100: true },
        'src/assets/js/admin/oidc-clients.ts': { 100: true },
        'src/assets/js/admin/oidc-clients/form.ts': { 100: true },
        'src/assets/js/admin/users.ts': { 100: true },
        'src/assets/js/admin/users/form.ts': { 100: true },
        'src/assets/js/admin/users/activities.ts': { 100: true },
        'src/assets/js/admin/users/data-mgmt.ts': { 100: true },
        'src/assets/js/main.ts': { 100: true },
        'src/assets/js/user.ts': { 100: true },
        'src/assets/js/utils/dialog.ts': { 100: true },
        'src/assets/js/utils/file-upload.ts': { 100: true },
        'src/assets/js/utils/form-helpers.ts': { 100: true },
        'src/assets/js/utils/tooltip.ts': { 100: true },
        'src/assets/js/webauthn/authenticate.ts': { 100: true },
        'src/assets/js/webauthn/register.ts': { 100: true },
        'src/assets/js/sw/register.ts': { 100: true },
        'src/assets/js/sw/service-worker.ts': { 100: true },
        'src/assets/js/vendor/alpine.ts': { 100: true },
        'src/assets/js/vendor/fingerprintjs.ts': { 100: true },
        'src/assets/js/vendor/lucide.ts': { 100: true },
        'src/assets/js/admin/activities/index.ts': { 100: true },
        'src/assets/js/admin/configuration/custom-identifiers.ts': {
          100: true,
        },
        'src/assets/js/admin/configuration/validation.ts': { 100: true },
        'src/assets/js/admin/grants/index.ts': { 100: true },
        'src/assets/js/admin/jwks.ts': { 100: true },
        'src/assets/js/admin/sessions/index.ts': { 100: true },
        'src/assets/js/account/apps.ts': { 100: true },
        'src/assets/js/account/layout.ts': { 100: true },
        'src/assets/js/account/recovery-codes.ts': { 100: true },
        'src/assets/js/account/sessions.ts': { 100: true },
        'src/assets/js/account/settings/avatar.ts': { 100: true },
        'src/assets/js/account/settings/confirm-handler.ts': { 100: true },
        'src/assets/js/account/settings/index.ts': { 100: true },
        'src/assets/js/account/settings/language.ts': { 100: true },
        'src/assets/js/account/settings/mfa.ts': { 100: true },
        'src/assets/js/account/settings/passkeys.ts': { 100: true },
        'src/assets/js/account/settings/password.ts': { 100: true },
        'src/assets/js/account/settings/password-visibility.ts': { 100: true },
        'src/assets/js/admin/settings.ts': { 100: true },
        'src/assets/js/admin/settings/application.ts': { 100: true },
        'src/assets/js/admin/settings/branding.ts': { 100: true },
        'src/assets/js/admin/settings/common.ts': { 100: true },
        'src/assets/js/admin/settings/deployment.ts': { 100: true },
        'src/assets/js/admin/settings/features.ts': { 100: true },
        'src/assets/js/admin/settings/import.ts': { 100: true },
        'src/assets/js/admin/settings/integrations.ts': { 100: true },
        'src/assets/js/admin/settings/oidc.ts': { 100: true },
        'src/assets/js/admin/settings/overview.ts': { 100: true },
        'src/assets/js/admin/settings/security.ts': { 100: true },
        'src/config/computed-fields.ts': { 100: true },
        'src/config/constants.ts': { 100: true },
        'src/config/hardening-defaults.ts': { 100: true },
        'src/config/i18n.ts': { 100: true },
        'src/config/index.ts': { 100: true },
        'src/config/provider/abstract.ts': { 100: true },
        'src/config/provider/bootstrap-provider.ts': { 100: true },
        'src/config/provider/db-provider.ts': { 100: true },
        'src/config/provider/file-provider.ts': { 100: true },
        'src/config/schemas/bootstrap-schema.ts': { 100: true },
        'src/config/schemas/schema.ts': { 100: true },
        'src/config/types.ts': { 100: true },
        'src/config/validation/persistence-validator.ts': { 100: true },
        'src/db/connection.ts': { 100: true },
        'src/db/extensions/tenant.extension.ts': { 100: true },
        'src/db/plugins/paginate.plugin.ts': { 100: true },
        'src/db/plugins/tenant.plugin.ts': { 100: true },
        'src/db/plugins/to-json.plugin.ts': { 100: true },
        'src/db/prisma.ts': { 100: true },
        'src/db/repositories/mongoose/activity.repository.ts': { 100: true },
        'src/db/repositories/mongoose/base.repository.ts': { 100: true },
        'src/db/repositories/mongoose/settings.repository.ts': { 100: true },
        'src/db/repositories/mongoose/social-integration.repository.ts': {
          100: true,
        },
        'src/db/repositories/mongoose/tenant-settings-override.repository.ts': {
          100: true,
        },
        'src/db/repositories/mongoose/tenant.repository.ts': { 100: true },
        'src/db/repositories/mongoose/user.repository.ts': { 100: true },
        'src/db/repositories/prisma/activity.repository.ts': { 100: true },
        'src/db/repositories/prisma/base.repository.ts': { 100: true },
        'src/db/repositories/prisma/settings.repository.ts': { 100: true },
        'src/db/repositories/prisma/social-integration.repository.ts': {
          100: true,
        },
        'src/db/repositories/prisma/tenant-settings-override.repository.ts': {
          100: true,
        },
        'src/db/repositories/prisma/tenant.repository.ts': { 100: true },
        'src/db/repositories/prisma/user.repository.ts': { 100: true },
        'src/db/utils.ts': { 100: true },
        'src/models/activity.model.ts': { 100: true },
        'src/models/base.model.ts': { 100: true },
        'src/models/jwks-key.model.ts': { 100: true },
        'src/models/settings.model.ts': { 100: true },
        'src/models/settings/application.ts': { 100: true },
        'src/models/settings/branding/ui/customization/views/accounts.ts': {
          100: true,
        },
        'src/models/settings/branding/ui/customization/views/auth.ts': {
          100: true,
        },
        'src/models/settings/branding/ui/customization/views/errorpage.ts': {
          100: true,
        },
        'src/models/settings/branding/ui/customization/views/oidc.ts': {
          100: true,
        },
        'src/models/settings/schemas.ts': { 100: true },
        'src/models/settings/types.ts': { 100: true },
        'src/models/social-integration.model.ts': { 100: true },
        'src/models/tenant-settings-override/model.ts': { 100: true },
        'src/models/tenant.model.ts': { 100: true },
        'src/models/user.model.ts': { 100: true },
        'src/types/tenant.ts': { 100: true },
        'src/types/user.ts': { 100: true },
        'src/services/activity.service.ts': { 100: true },
        'src/services/auth.service.ts': { 100: true },
        'src/services/base.service.ts': { 100: true },
        'src/services/data-transfer/data-transfer.service.ts': { 100: true },
        'src/services/data-transfer/entities/activities.entity.ts': {
          100: true,
        },
        'src/services/data-transfer/entities/index.ts': { 100: true },
        'src/services/data-transfer/entities/oidc-clients.entity.ts': {
          100: true,
        },
        'src/services/data-transfer/entities/users.entity.ts': { 100: true },
        'src/services/data-transfer/format-utils.ts': { 100: true },
        'src/services/geolocation.service.ts': { 100: true },
        'src/services/i18n.service.ts': { 100: true },
        'src/services/image-processor.service.ts': { 100: true },
        'src/services/ip-reputation.service.ts': { 100: true },
        'src/services/notification.service.ts': { 100: true },
        'src/services/ops-social-callback.service.ts': { 100: true },
        'src/services/platform-admin.service.ts': { 100: true },
        'src/services/recovery.service.ts': { 100: true },
        'src/services/redis-pubsub.service.ts': { 100: true },
        'src/services/settings.service.ts': { 100: true },
        'src/services/sms.service.ts': { 100: true },
        'src/services/social-integration.service.ts': { 100: true },
        'src/services/social-tier1-completion.service.ts': { 100: true },
        'src/services/tenant-settings-override.service.ts': { 100: true },
        'src/services/user.service.ts': { 100: true },
        'src/services/webauthn.service.ts': { 100: true },
        'src/api/v1/errors.ts': { 100: true },
        'src/api/v1/response.ts': { 100: true },
        'src/api/v1/scopes.ts': { 100: true },
        'src/api/v1/validators/audit.validator.ts': { 100: true },
        'src/api/v1/validators/clients.validator.ts': { 100: true },
        'src/api/v1/validators/jwks.validator.ts': { 100: true },
        'src/api/v1/validators/registration-tokens.validator.ts': {
          100: true,
        },
        'src/api/v1/validators/sessions.validator.ts': { 100: true },
        'src/api/v1/validators/tenants.validator.ts': { 100: true },
        'src/api/v1/validators/users.validator.ts': { 100: true },
        'src/api/v1/routes/index.ts': { 100: true },
        'src/api/v1/routes/audit.routes.ts': { 100: true },
        'src/api/v1/routes/clients.routes.ts': { 100: true },
        'src/api/v1/routes/jwks.routes.ts': { 100: true },
        'src/api/v1/routes/registration-tokens.routes.ts': { 100: true },
        'src/api/v1/routes/sessions.routes.ts': { 100: true },
        'src/api/v1/routes/stats.routes.ts': { 100: true },
        'src/api/v1/routes/tenants.routes.ts': { 100: true },
        'src/api/v1/routes/users.routes.ts': { 100: true },
        'src/api/v1/controllers/audit.controller.ts': { 100: true },
        'src/api/v1/controllers/clients.controller.ts': { 100: true },
        'src/api/v1/controllers/jwks.controller.ts': { 100: true },
        'src/api/v1/controllers/registration-tokens.controller.ts': {
          100: true,
        },
        'src/api/v1/controllers/sessions.controller.ts': { 100: true },
        'src/api/v1/controllers/stats.controller.ts': { 100: true },
        'src/api/v1/controllers/tenants.controller.ts': { 100: true },
        'src/api/v1/controllers/users.controller.ts': { 100: true },
        'src/api/v1/middleware/audit-logger.middleware.ts': { 100: true },
        'src/api/v1/middleware/error-handler.middleware.ts': { 100: true },
        'src/api/v1/middleware/jwt-auth.middleware.ts': { 100: true },
        'src/api/v1/middleware/rate-limiter.middleware.ts': { 100: true },
        'src/api/v1/middleware/scope-guard.middleware.ts': { 100: true },
        'src/api/v1/middleware/validate-body.middleware.ts': { 100: true },
        'src/api/v1/middleware/validate-query.middleware.ts': { 100: true },
        'src/api/v1/pagination.ts': { 100: true },
        'src/errors/platform.errors.ts': { 100: true },
        'src/observability/index.ts': { 100: true },
        'src/observability/logs/constants.ts': { 100: true },
        'src/observability/logs/logger.ts': { 100: true },
        'src/observability/metrics/metrics.service.ts': { 100: true },
        'src/di/loaders/adapter-loader.ts': { 100: true },
        'src/di/loaders/optional-deps.ts': { 100: true },
        'src/di/index.ts': { 100: true },
        'src/di/modules/api.module.ts': { 100: true },
        'src/di/modules/app.module.ts': { 100: true },
        'src/di/modules/config.module.ts': { 100: true },
        'src/di/modules/controllers.module.ts': { 100: true },
        'src/di/modules/database.module.ts': { 100: true },
        'src/di/modules/middleware.module.ts': { 100: true },
        'src/di/modules/models.module.ts': { 100: true },
        'src/di/modules/oidc.module.ts': { 100: true },
        'src/di/modules/services.module.ts': { 100: true },
        'src/di/modules/storage.module.ts': { 100: true },
        'src/di/types.ts': { 100: true },
        'src/di/validation.ts': { 100: true },
        'src/controllers/account.controller.ts': { 100: true },
        'src/controllers/auth.controller.ts': { 100: true },
        'src/controllers/admin/activity.controller.ts': { 100: true },
        'src/controllers/admin/configuration.controller.ts': { 100: true },
        'src/controllers/admin/data-transfer.controller.ts': { 100: true },
        'src/controllers/admin/grant.controller.ts': { 100: true },
        'src/controllers/admin/home.controller.ts': { 100: true },
        'src/controllers/admin/jwks.controller.ts': { 100: true },
        'src/controllers/admin/oidc-client.controller.ts': { 100: true },
        'src/controllers/admin/platform.controller.ts': { 100: true },
        'src/controllers/admin/session.controller.ts': { 100: true },
        'src/controllers/admin/settings.controller.ts': { 100: true },
        'src/controllers/admin/user.controller.ts': { 100: true },
        'src/controllers/webauthn.controller.ts': { 100: true },
        'src/routes/webauthn.ts': { 100: true },
        'src/routes/ops.ts': { 100: true },
        'src/routes/index.ts': { 100: true },
        'src/routes/accounts.ts': { 100: true },
        'src/routes/admin.ts': { 100: true },
        'src/routes/auth.ts': { 100: true },
        'src/routes/media.ts': { 100: true },
        'src/middlewares/async-handler.ts': { 100: true },
        'src/middlewares/config-validation.middleware.ts': { 100: true },
        'src/middlewares/html-error-handler.middleware.ts': { 100: true },
        'src/middlewares/locals.middleware.ts': { 100: true },
        'src/middlewares/mongo-sanitize.middleware.ts': { 100: true },
        'src/middlewares/ops-tenant.middleware.ts': { 100: true },
        'src/middlewares/platform-tenant.middleware.ts': { 100: true },
        'src/middlewares/precompressed-static.middleware.ts': { 100: true },
        'src/middlewares/request-logger.middleware.ts': { 100: true },
        'src/middlewares/security.middleware.ts': { 100: true },
        'src/middlewares/tenant-context.middleware.ts': { 100: true },
        'src/middlewares/ui.middleware.ts': { 100: true },
        'src/middlewares/upload.middleware.ts': { 100: true },
        'src/middlewares/validate-html.middleware.ts': { 100: true },
        'src/middlewares/validate-json-legacy.middleware.ts': { 100: true },
        'src/middlewares/vary-headers.middleware.ts': { 100: true },
        'src/multi-tenancy/master-tenant-bootstrap.ts': { 100: true },
        'src/multi-tenancy/redis-key.ts': { 100: true },
        'src/multi-tenancy/tenant-context.ts': { 100: true },
        'src/multi-tenancy/tenant-issuer.ts': { 100: true },
        'src/multi-tenancy/tenant-provider-registry.ts': { 100: true },
        'src/integration/base-oauth2-social-login.ts': { 100: true },
        'src/integration/base-oidc-social-login.ts': { 100: true },
        'src/integration/base-social-login.ts': { 100: true },
        'src/integration/facebook-social-login.ts': { 100: true },
        'src/integration/github-social-login.ts': { 100: true },
        'src/integration/google-social-login.ts': { 100: true },
        'src/integration/linkedin-social-login.ts': { 100: true },
        'src/integration/microsoft-social-login.ts': { 100: true },
        'src/integration/social-login-errors.ts': { 100: true },
        'src/integration/social-login-manager.ts': { 100: true },
        'src/integration/social-tier-utils.ts': { 100: true },
        'src/storage/local-storage.provider.ts': { 100: true },
        'src/storage/s3-storage.provider.ts': { 100: true },
        'src/storage/signed-url.ts': { 100: true },
        'src/storage/storage-provider.interface.ts': { 100: true },
        'src/validators/base-schemas.ts': { 100: true },
        'src/validators/listing-query.ts': { 100: true },
        'src/validators/parse.ts': { 100: true },
        'src/validators/admin/activities.ts': { 100: true },
        'src/validators/admin/grants.ts': { 100: true },
        'src/validators/admin/oidc-clients.ts': { 100: true },
        'src/validators/admin/sessions.ts': { 100: true },
        'src/validators/admin/users.ts': { 100: true },
        'src/validators/auth/logout.ts': { 100: true },
        'src/validators/auth/mfa.ts': { 100: true },
        'src/validators/auth/oauth-callback.ts': { 100: true },
        'src/validators/auth/query-params.ts': { 100: true },
        'src/validators/auth/social.ts': { 100: true },
        'src/validators/oidc/handlers.ts': { 100: true },
        'src/validators/webauthn/registration.ts': { 100: true },
        'src/validators/webauthn/rename.ts': { 100: true },
        'src/utils/activity-logger.factory.ts': { 100: true },
        'src/utils/client-info.ts': { 100: true },
        'src/utils/client-registry-config.ts': { 100: true },
        'src/utils/client-transformer.ts': { 100: true },
        'src/utils/config-file-reader.ts': { 100: true },
        'src/utils/config-merge.ts': { 100: true },
        'src/utils/connect-redis-client.ts': { 100: true },
        'src/utils/cookies.ts': { 100: true },
        'src/utils/custom-identifier-validation.ts': { 100: true },
        'src/utils/content-security-policy.ts': { 100: true },
        'src/utils/env-interpolation.ts': { 100: true },
        'src/utils/env-validator.ts': { 100: true },
        'src/utils/encryption.ts': { 100: true },
        'src/utils/email.ts': { 100: true },
        'src/utils/filesystem.ts': { 100: true },
        'src/utils/flash-redirect.ts': { 100: true },
        'src/utils/guard-error.ts': { 100: true },
        'src/utils/hmac-state.ts': { 100: true },
        'src/utils/key-encryption.ts': { 100: true },
        'src/utils/mfa.ts': { 100: true },
        'src/utils/misc.ts': { 100: true },
        'src/utils/nested-value.ts': { 100: true },
        'src/utils/password-breach.ts': { 100: true },
        'src/utils/password.ts': { 100: true },
        'src/utils/prisma-session-store.ts': { 100: true },
        'src/utils/rate-limiter.ts': { 100: true },
        'src/utils/recovery.ts': { 100: true },
        'src/utils/redirect-authority.ts': { 100: true },
        'src/utils/session.ts': { 100: true },
        'src/utils/settings.helper.ts': { 100: true },
        'src/utils/shutdown.ts': { 100: true },
        'src/utils/view-resolver.ts': { 100: true },
        'src/utils/views.ts': { 100: true },
        'src/oidc/config.ts': { 100: true },
        'src/oidc/client-merger.ts': { 100: true },
        'src/oidc/adapter/client.interface.ts': { 100: true },
        'src/oidc/adapter/index.ts': { 100: true },
        'src/oidc/adapter/base.ts': { 100: true },
        'src/oidc/adapter/client-crud-utils.ts': { 100: true },
        'src/oidc/adapter/mongodb/admin-service.ts': { 100: true },
        'src/oidc/adapter/mongodb/index.ts': { 100: true },
        'src/oidc/adapter/prisma/admin-service.ts': { 100: true },
        'src/oidc/adapter/prisma/index.ts': { 100: true },
        'src/oidc/adapter/redis/admin-service.ts': { 100: true },
        'src/oidc/adapter/redis/index.ts': { 100: true },
        'src/oidc/index.ts': { 100: true },
        'src/oidc/listener.ts': { 100: true },
        'src/oidc/provider.ts': { 100: true },
        'src/oidc/provider-keystore-updater.ts': { 100: true },
        'src/oidc/utils.ts': { 100: true },
        'src/oidc/key-store/constants.ts': { 100: true },
        'src/oidc/key-store/db-key-store.ts': { 100: true },
        'src/oidc/key-store/file-key-store.ts': { 100: true },
        'src/oidc/key-store/mongoose-jwks-key.repository.ts': { 100: true },
        'src/oidc/key-store/prisma-jwks-key.repository.ts': { 100: true },
        'src/oidc/flows/route.ts': { 100: true },
        'src/oidc/flows/handlers/abort.ts': { 100: true },
        'src/oidc/flows/middleware/cache.middleware.ts': { 100: true },
        'src/oidc/flows/middleware/koa.middleware.ts': { 100: true },
        'src/oidc/flows/middleware/oidc.middleware.ts': { 100: true },
        'src/oidc/middleware/cache-headers.ts': { 100: true },
        'src/oidc/flows/handlers/consent.ts': { 100: true },
        'src/oidc/flows/handlers/error.ts': { 100: true },
        'src/oidc/flows/handlers/interaction.ts': { 100: true },
        'src/oidc/flows/handlers/login.ts': { 100: true },
        'src/oidc/flows/handlers/mfa.ts': { 100: true },
        'src/oidc/flows/handlers/new-device-verify.ts': { 100: true },
        'src/oidc/flows/handlers/select-account.ts': { 100: true },
        'src/oidc/flows/handlers/social-callback.ts': { 100: true },
        'src/oidc/flows/handlers/social-login.ts': { 100: true },
        'src/oidc/flows/handlers/webauthn-mfa.ts': { 100: true },
        'src/oidc/specs/*.ts': { 100: true },
        'src/oidc/specs/feature.ts': { 100: true },
        'src/oidc/specs/feature/**/*.ts': { 100: true },
        'src/oidc/specs/feature/device-flow.ts': { 100: true },
        'src/oidc/specs/feature/rp-initiated-logout.ts': { 100: true },
      },
    },

    // Test timeout
    testTimeout: 10000,
    hookTimeout: 120000,

    // Setup files
    setupFiles: [],

    // Global test configuration
    globals: true,

    // TypeScript configuration
    typecheck: {
      tsconfig: './tsconfig.json',
    },

    // Reporter configuration
    reporters: ['verbose', 'json', 'html'],
    outputFile: {
      json: './test-results/test-results.json',
      html: './test-results/test-results.html',
    },
  },

  // Resolve configuration
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
    },
  },
});
