/**
 * Computed Fields System
 *
 * This module handles auto-generated secrets and derived configuration fields.
 * It ensures that certain fields are automatically computed from base configuration
 * values, reducing duplication and maintaining consistency.
 *
 * @module config/computed-fields
 */

import crypto from 'node:crypto';
import {
  tenantContext,
  DEFAULT_TENANT_ID,
} from '../multi-tenancy/tenant-context.js';
import { getNestedValue, setNestedValue } from '../utils/nested-value.js';

/**
 * Registry of computed field paths organized by computation type
 */
export const COMPUTED_FIELDS = {
  /**
   * Auto-generated secret fields that should be created if they don't exist.
   * These are generated once and then persisted.
   */
  autoGenerated: [
    'security.secrets.jwt_secret',
    'security.secrets.cookie_secrets',
    'security.secrets.hmac_secret',
    'oidc.secrets.pairwise_salt',
  ] as const,

  /**
   * Derived fields that are always computed from other configuration values.
   * These fields are recalculated on every config load/update.
   */
  derived: [
    // OIDC URLs derived from deployment.url and oidc.path
    'oidc.issuer',
    'oidc.discovery.op_policy_uri',
    'oidc.discovery.op_tos_uri',
    'oidc.discovery.service_documentation',

    // MFA fields derived from company name and deployment URL
    'security.authentication.multi_factor.totp.issuer_name',
    'security.authentication.multi_factor.webauthn.rp_name',
    'security.authentication.multi_factor.webauthn.rp_id',
  ] as const,
} as const;

/**
 * Type representing the result of checking if a field is computed
 */
export interface ComputedFieldInfo {
  isComputed: boolean;
  type: 'auto-generated' | 'derived' | 'user-provided';
}

/**
 * Generates a cryptographically secure random secret
 *
 * @param length - Length of the secret in bytes (default: 64)
 * @returns Hex-encoded random string (2x length in characters)
 *
 * @example
 * ```typescript
 * const secret = generateSecureSecret(32);
 * // Returns 64-character hex string
 * ```
 */
export function generateSecureSecret(length: number = 64): string {
  return crypto.randomBytes(length).toString('hex');
}

/**
 * Extracts hostname from a URL string
 *
 * @param url - URL string to parse
 * @returns Hostname from the URL, or 'localhost' if parsing fails
 *
 * @example
 * ```typescript
 * getHostnameFromUrl('https://auth.example.com:3000/path')
 * // Returns: 'auth.example.com'
 *
 * getHostnameFromUrl('invalid-url')
 * // Returns: 'localhost'
 * ```
 */
export function getHostnameFromUrl(url: string): string {
  try {
    const parsedUrl = new URL(url);
    return parsedUrl.hostname;
  } catch {
    // If URL parsing fails, return localhost as safe fallback
    return 'localhost';
  }
}

/**
 * Determines if a field path is a computed field and its computation type
 *
 * @param fieldPath - Dot-notation path to the field (e.g., 'security.secrets.jwt_secret')
 * @returns Object containing computation status and type
 *
 * @example
 * ```typescript
 * isComputedField('security.secrets.jwt_secret')
 * // Returns: { isComputed: true, type: 'auto-generated' }
 *
 * isComputedField('oidc.issuer')
 * // Returns: { isComputed: true, type: 'derived' }
 *
 * isComputedField('deployment.url')
 * // Returns: { isComputed: false, type: 'user-provided' }
 * ```
 */
export function isComputedField(fieldPath: string): ComputedFieldInfo {
  if (COMPUTED_FIELDS.autoGenerated.includes(fieldPath as any)) {
    return {
      isComputed: true,
      type: 'auto-generated',
    };
  }

  if (COMPUTED_FIELDS.derived.includes(fieldPath as any)) {
    return {
      isComputed: true,
      type: 'derived',
    };
  }

  // Field is user-provided
  return {
    isComputed: false,
    type: 'user-provided',
  };
}

/**
 * Check if a secret should be regenerated.
 * Only regenerate if null/undefined, NOT empty string (which indicates corruption).
 *
 * SECURITY NOTE: Empty strings in secret fields typically indicate database corruption
 * or improper handling. Regenerating in this case could:
 * - Invalidate existing tokens/sessions unexpectedly
 * - Create inconsistent state between instances
 * - Mask the underlying data integrity issue
 *
 * To regenerate a corrupted secret, explicitly delete the field from the database.
 *
 * @param value - Value to check
 * @param fieldPath - Field path for logging (e.g., 'security.secrets.jwt_secret')
 * @returns True if secret should be generated (only for null/undefined)
 */
function isSecretMissing(value: any, fieldPath: string): boolean {
  // null/undefined = never set, safe to generate
  if (value === null || value === undefined) {
    return true;
  }

  if (value === '') {
    console.warn(
      `[CONFIG WARNING] Empty string for secret "${fieldPath}". ` +
        'This may indicate data corruption. Delete the field to trigger regeneration.'
    );
    return false;
  }

  // Empty array = never set (for array secrets like cookie_secrets)
  if (Array.isArray(value) && value.length === 0) {
    return true;
  }

  // Has a value, don't regenerate
  return false;
}

/**
 * Applies computed defaults to a configuration object
 *
 * This function performs two types of computation:
 * 1. Auto-generated secrets: Only generated if field is empty (preserves existing values)
 * 2. Derived fields: Always computed from base values (overrides existing values)
 *
 * Base values used for computation:
 * - deploymentUrl: deployment.url
 * - oidcPath: oidc.path
 * - companyName: branding.companyName
 *
 * @param config - Partial configuration object to apply defaults to
 * @returns Configuration object with computed defaults applied
 *
 * @example
 * ```typescript
 * const config = {
 *   deployment: { url: 'https://auth.example.com' },
 *   oidc: { path: '/oidc/v1' },
 *   branding: { companyName: 'Example Corp' },
 * };
 *
 * const withDefaults = applyComputedDefaults(config);
 * // Result includes:
 * // - Auto-generated secrets (if they were empty)
 * // - oidc.issuer = 'https://auth.example.com/oidc/v1'
 * // - security.authentication.multi_factor.totp.issuer_name = 'Example Corp'
 * // - etc.
 * ```
 */
export function applyComputedDefaults(config: any): any {
  // Create a deep copy to avoid mutating the original
  const result = JSON.parse(JSON.stringify(config));

  const deploymentUrl =
    (getNestedValue(result, 'deployment.url') as string) || '';
  const oidcPath =
    (getNestedValue(result, 'oidc.path') as string) || '/oidc/v1';
  const companyName =
    (getNestedValue(result, 'branding.companyName') as string) || 'Parako.ID';

  // STEP 1: Auto-generate secrets if they don't exist
  // These are only generated once and then persisted

  // security.secrets.jwt_secret
  const jwtSecret = getNestedValue(result, 'security.secrets.jwt_secret');
  if (isSecretMissing(jwtSecret, 'security.secrets.jwt_secret')) {
    setNestedValue(
      result,
      'security.secrets.jwt_secret',
      generateSecureSecret(64)
    );
  }

  // security.secrets.cookie_secrets
  const cookieSecrets = getNestedValue(
    result,
    'security.secrets.cookie_secrets'
  );
  if (isSecretMissing(cookieSecrets, 'security.secrets.cookie_secrets')) {
    setNestedValue(result, 'security.secrets.cookie_secrets', [
      generateSecureSecret(64),
      generateSecureSecret(64),
    ]);
  }

  // security.secrets.hmac_secret
  const hmacSecret = getNestedValue(result, 'security.secrets.hmac_secret');
  if (isSecretMissing(hmacSecret, 'security.secrets.hmac_secret')) {
    setNestedValue(
      result,
      'security.secrets.hmac_secret',
      generateSecureSecret(64)
    );
  }

  // oidc.secrets.pairwise_salt
  const pairwiseSalt = getNestedValue(result, 'oidc.secrets.pairwise_salt');
  if (isSecretMissing(pairwiseSalt, 'oidc.secrets.pairwise_salt')) {
    setNestedValue(
      result,
      'oidc.secrets.pairwise_salt',
      generateSecureSecret(32)
    );
  }

  // STEP 2: Always compute derived fields
  // These are recalculated on every config load/update from base values

  // ─── Tenant-aware base URL derivation ────────────────────────────────
  // When running inside a tenant context (non-default), derive URLs from
  // the tenant's subdomain or custom domain instead of the platform URL.
  // Priority: 1. explicit oidc.issuer_url  2. tenant_domain  3. subdomain
  const explicitIssuerUrl = getNestedValue(result, 'oidc.issuer_url') as
    | string
    | undefined;
  const tenantDomain = getNestedValue(result, 'tenant_domain') as
    | string
    | undefined;
  const tenantId = tenantContext.getTenantIdSafe();
  const isTenantContext =
    tenantId !== undefined && tenantId !== DEFAULT_TENANT_ID;

  let tenantBaseUrl: string | null = null;
  if (isTenantContext && deploymentUrl) {
    const protocol = deploymentUrl.startsWith('https://')
      ? 'https://'
      : 'http://';
    if (tenantDomain) {
      tenantBaseUrl = `${protocol}${tenantDomain}`;
    } else {
      // Subdomain: {protocol}{tenantId}.{baseDomain}
      // Preserve port if present (e.g., parako.id:8443 → acme.parako.id:8443)
      const baseDomain = deploymentUrl.replace(/^https?:\/\//, '');
      tenantBaseUrl = `${protocol}${tenantId}.${baseDomain}`;
    }
  }

  // The effective base URL for OIDC and discovery URLs
  const effectiveBaseUrl = tenantBaseUrl || deploymentUrl;

  // OIDC URLs derived from deployment.url and oidc.path
  if (effectiveBaseUrl) {
    // oidc.issuer: explicit issuer_url takes precedence, then derived
    if (explicitIssuerUrl) {
      setNestedValue(result, 'oidc.issuer', explicitIssuerUrl);
    } else {
      setNestedValue(result, 'oidc.issuer', `${effectiveBaseUrl}${oidcPath}`);
    }

    // OIDC discovery document URLs — use effective base URL as default,
    // but preserve tenant-set values (these are TENANT-customizable per reasoning doc).
    const existingPolicyUri = getNestedValue(
      result,
      'oidc.discovery.op_policy_uri'
    );
    if (!existingPolicyUri) {
      setNestedValue(
        result,
        'oidc.discovery.op_policy_uri',
        `${effectiveBaseUrl}/privacy`
      );
    }

    const existingTosUri = getNestedValue(result, 'oidc.discovery.op_tos_uri');
    if (!existingTosUri) {
      setNestedValue(
        result,
        'oidc.discovery.op_tos_uri',
        `${effectiveBaseUrl}/terms`
      );
    }

    const existingServiceDoc = getNestedValue(
      result,
      'oidc.discovery.service_documentation'
    );
    if (!existingServiceDoc) {
      setNestedValue(
        result,
        'oidc.discovery.service_documentation',
        `${effectiveBaseUrl}/docs`
      );
    }

    // Integration URLs - only set defaults if empty (don't overwrite user values)
    const website = getNestedValue(result, 'integrations.urls.website');
    if (!website) {
      setNestedValue(result, 'integrations.urls.website', effectiveBaseUrl);
    }

    const privacyPolicy = getNestedValue(
      result,
      'integrations.urls.privacy_policy'
    );
    if (!privacyPolicy) {
      setNestedValue(
        result,
        'integrations.urls.privacy_policy',
        `${effectiveBaseUrl}/privacy`
      );
    }

    const termsOfService = getNestedValue(
      result,
      'integrations.urls.terms_of_service'
    );
    if (!termsOfService) {
      setNestedValue(
        result,
        'integrations.urls.terms_of_service',
        `${effectiveBaseUrl}/terms`
      );
    }

    const contact = getNestedValue(result, 'integrations.urls.contact');
    if (!contact) {
      setNestedValue(
        result,
        'integrations.urls.contact',
        `${effectiveBaseUrl}/contact`
      );
    }
  }

  // MFA fields derived from companyName and deploymentUrl
  // Only set these if not already specified by user
  if (companyName) {
    // TOTP issuer name - only set if not already specified
    const existingIssuerName = getNestedValue(
      result,
      'security.authentication.multi_factor.totp.issuer_name'
    );
    if (!existingIssuerName || existingIssuerName === 'OIDC Provider') {
      setNestedValue(
        result,
        'security.authentication.multi_factor.totp.issuer_name',
        companyName
      );
    }

    // WebAuthn relying party name - only set if not already specified
    const existingRpName = getNestedValue(
      result,
      'security.authentication.multi_factor.webauthn.rp_name'
    );
    if (!existingRpName || existingRpName === 'OIDC Provider') {
      setNestedValue(
        result,
        'security.authentication.multi_factor.webauthn.rp_name',
        companyName
      );
    }
  }

  // WebAuthn RP ID derived from effective base URL hostname.
  // For custom domain tenants, use the custom domain hostname.
  // For subdomain tenants, use the base domain (rp_id must be an ancestor of the origin).
  // For platform/default, use the deployment URL hostname.
  if (effectiveBaseUrl || deploymentUrl) {
    const existingRpId = getNestedValue(
      result,
      'security.authentication.multi_factor.webauthn.rp_id'
    );
    if (!existingRpId || existingRpId === 'localhost') {
      let rpId: string;
      if (isTenantContext && tenantDomain) {
        // Custom domain: use the domain directly as rp_id
        rpId = tenantDomain;
      } else {
        // Subdomain or default: use the base domain (ancestor of any subdomain)
        rpId = getHostnameFromUrl(deploymentUrl);
      }
      setNestedValue(
        result,
        'security.authentication.multi_factor.webauthn.rp_id',
        rpId
      );
    }
  }

  return result;
}
